version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.8.2-node
        environment:
          MIX_ENV: test
      - image: circleci/postgres:11.2-alpine-postgis-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: re_test
          POSTGRES_PASSWORD:

    working_directory: ~/app

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - $CACHE_VERSION-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - $CACHE_VERSION-mix-cache-{{ .Branch }}
            - $CACHE_VERSION-mix-cache
      - restore_cache:
          keys:
            - $CACHE_VERSION-build-cache-{{ .Branch }}
            - $CACHE_VERSION-build-cache
      - run: mix deps.get
      - run: mix compile --warnings-as-errors --force
      - run: mix format --check-formatted --dry-run
      - save_cache:
          key: $CACHE_VERSION-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: $CACHE_VERSION-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: $CACHE_VERSION-mix-cache
          paths: "deps"
      - save_cache:
          key: $CACHE_VERSION-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: $CACHE_VERSION-build-cache
          paths: "_build"

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: mix do compile --warnings-as-errors, coveralls.json

      - run: MIX_ENV=test mix absinthe.schema.json --schema ReWeb.Schema --json-codec AbsintheSortingCodec --pretty
      - run: sudo npm install --global apollo
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            apollo service:push -c=priv/apollo/apollo.staging.config.js --key=$APOLLO_STAGING_TOKEN
            apollo service:push -c=priv/apollo/apollo.prod.config.js --key=$APOLLO_PRODUCTION_TOKEN
          fi

      - run: curl -s https://codecov.io/bash | bash

      - store_test_results:
          path: _build/test/lib/re/
      - store_test_results:
          path: _build/test/lib/re_web/
      - store_test_results:
          path: _build/test/lib/re_integrations/
